<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Message', 'doctrine');

/**
 * BaseMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $theme
 * @property text $mesage
 * @property User $User
 * 
 * @method integer getUserId()  Returns the current record's "user_id" value
 * @method integer getTheme()   Returns the current record's "theme" value
 * @method text    getMesage()  Returns the current record's "mesage" value
 * @method User    getUser()    Returns the current record's "User" value
 * @method Message setUserId()  Sets the current record's "user_id" value
 * @method Message setTheme()   Sets the current record's "theme" value
 * @method Message setMesage()  Sets the current record's "mesage" value
 * @method Message setUser()    Sets the current record's "User" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('theme', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('mesage', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('type', 'MYISAM');
        $this->option('collate', 'utf8_hungarian_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}