<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('News', 'doctrine');

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $create_date
 * @property varchar $title_hu
 * @property varchar $title_en
 * @property varchar $title_ru
 * @property varchar $title_pl
 * @property text $news_hu
 * @property text $news_en
 * @property text $news_ru
 * @property text $news_pl
 * 
 * @method timestamp getCreateDate()  Returns the current record's "create_date" value
 * @method varchar   getTitleHu()     Returns the current record's "title_hu" value
 * @method varchar   getTitleEn()     Returns the current record's "title_en" value
 * @method varchar   getTitleRu()     Returns the current record's "title_ru" value
 * @method varchar   getTitlePl()     Returns the current record's "title_pl" value
 * @method text      getNewsHu()      Returns the current record's "news_hu" value
 * @method text      getNewsEn()      Returns the current record's "news_en" value
 * @method text      getNewsRu()      Returns the current record's "news_ru" value
 * @method text      getNewsPl()      Returns the current record's "news_pl" value
 * @method News      setCreateDate()  Sets the current record's "create_date" value
 * @method News      setTitleHu()     Sets the current record's "title_hu" value
 * @method News      setTitleEn()     Sets the current record's "title_en" value
 * @method News      setTitleRu()     Sets the current record's "title_ru" value
 * @method News      setTitlePl()     Sets the current record's "title_pl" value
 * @method News      setNewsHu()      Sets the current record's "news_hu" value
 * @method News      setNewsEn()      Sets the current record's "news_en" value
 * @method News      setNewsRu()      Sets the current record's "news_ru" value
 * @method News      setNewsPl()      Sets the current record's "news_pl" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('create_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('title_hu', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('title_en', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('title_ru', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('title_pl', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('news_hu', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('news_en', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('news_ru', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('news_pl', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('type', 'MYISAM');
        $this->option('collate', 'utf8_hungarian_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}