<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('User', 'doctrine');

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $email
 * @property varchar $name
 * @property varchar $tel
 * @property Doctrine_Collection $Message
 * 
 * @method varchar             getEmail()   Returns the current record's "email" value
 * @method varchar             getName()    Returns the current record's "name" value
 * @method varchar             getTel()     Returns the current record's "tel" value
 * @method Doctrine_Collection getMessage() Returns the current record's "Message" collection
 * @method User                setEmail()   Sets the current record's "email" value
 * @method User                setName()    Sets the current record's "name" value
 * @method User                setTel()     Sets the current record's "tel" value
 * @method User                setMessage() Sets the current record's "Message" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('email', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('name', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('tel', 'varchar', 20, array(
             'type' => 'varchar',
             'length' => 20,
             ));

        $this->option('type', 'MYISAM');
        $this->option('collate', 'utf8_hungarian_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Message', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}