# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing


sf_captchagd:
  url: /captcha
  param: { module: sfCaptchaGD, action: GetImage }

change_language:
  url:   /change_language
  param: { module: language, action: changeLanguage }


# default rules
  
main:
  url: /:sf_culture/main
  param: { module: news, action: mainpage }
  

hirlevel:
  url: /:sf_culture/hirlevel
  param: { module: user, action: new }
  
rolunk_mondtak:
  url: /:sf_culture/rolunk_mondtak
  param: { module: company, action: aboutUs }

elerhetosegek:
  url: /:sf_culture/elerhetosegek
  param: { module: company, action: contact }
  
cegunkrol:
  url: /:sf_culture/cegunkrol
  param: { module: company, action: cegunkrol }

amerin_mugyantas_padlok:
  url: /:sf_culture/amerin_mugyantas_padlok
  param: { module: product, action: mugyantas_padlok }

villamos_ipari_mugyantak:
  url: /:sf_culture/villamos_ipari_mugyantak
  param: { module: product, action: villamos_ipari_mugyantak }


localized_homepage:
  url:   /:sf_culture
  param: { module: news, action: mainpage }
  # requirements:
  #  sf_culture: (?:fr|en)


homepage:
  url:   /
  param: { module: news, action: index }



# generic rules
# please, remove them by adding more specific rules

default_index:
  url:   /:sf_culture/:module
  param: { action: index }

default:
  url:   /:sf_culture/:module/:action/*
